### ISSUE TITLE
Issue processing Channel 3 data

### ISSUE THREAD

**Issue by NicolasMonnier** [sidiso/surfh#4]
```
Traceback (most recent call last):
  File "/home/nmonnier/Projects/JWST/MRS/surfh/simulate_orion.py", line 109, in <module>
    data = spectro.forward(cube)
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/site-packages/aljabr/linop.py", line 205, in shape_checked
    outarray = func(self, inarray)
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/site-packages/aljabr/linop.py", line 164, in timed
    out = func(*args, **kwargs)
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/models.py", line 625, in forward
    out[self._idx[idx] : self._idx[idx + 1]] = chan.forward(blurred_f).ravel()
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/site-packages/aljabr/linop.py", line 205, in shape_checked
    outarray = func(self, inarray)
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/site-packages/aljabr/linop.py", line 164, in timed
    out = func(*args, **kwargs)
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/models.py", line 521, in forward
    gridded = self.gridding(blurred, pointing)
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/models.py", line 444, in gridding
    return sp.interpolate.interpn(
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 2709, in interpn
    raise ValueError("One of the requested xi is out of bounds "
ValueError: One of the requested xi is out of bounds in dimension 1

```

**Comment by NicolasMonnier** [comment]
New Error message with custom interpolation :

```
Traceback (most recent call last):
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/nmonnier/anaconda3/envs/mrs/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/AsyncProcessPoolLight.py", line 54, in _dispatch_job
    result = method(instance, *args, **kwargs)
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/models.py", line 600, in forward_multiproc
    gridded = self.gridding(blurred, pointing)
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/models.py", line 493, in gridding
    return cython_2D_interpolation.interpn( (alpha_axis, beta_axis),
  File "/home/nmonnier/Projects/JWST/MRS/surfh/surfh/cython_2D_interpolation.py", line 479, in interpn
    raise ValueError("One of the requested xi is out of bounds "
ValueError: One of the requested xi is out of bounds in dimension 0

```
